name: Deploy server

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'infra/flake.nix'
      - 'infra/flake.lock'
      - 'infra/pyproject.toml'
      - 'infra/uv.lock'

env:
  IMAGE_NAME: cfa-dagster
  IMAGE_TAG: ${{ (github.head_ref || github.ref_name) == 'master' && 'latest' || github.head_ref || github.ref_name }}
  # getting tag from branch name https://stackoverflow.com/a/71158878

jobs:
  build-and-push-image:
    runs-on: cfa-aca-gh-runner
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build image
        run: nix build

      - name: Push image ghcr.io
        id: push-ghcr
        run: |
            #bash toLowercase e.g. CDCgov -> cdcgov
            OWNER=${GITHUB_REPOSITORY_OWNER,,}
            REGISTRY_IMAGE="ghcr.io/$OWNER/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"

            skopeo copy \
            --dest-creds ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            "docker-archive:result" \
            "docker://$REGISTRY_IMAGE"

  deploy-container-app:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    environment: production
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZ_CLIENT_ID }}
          subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZ_TENANT_ID }}

      - name: Deploy Container App
        run: bash infra/deploy-container-app.sh
